# Generated by Django 6.0.5 on 2026-05-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('post_url', models.URLField(help_text='The direct URL to the Facebook post.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('post_content', models.TextField(help_text='The sanitized, full text content of the post.')),
                ('source_group', models.CharField(help_text='The name or identifier of the Facebook group where the post was found.', max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp of when this post was processed by the AI pipeline.', null=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
